/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_View;

import BLL.Autobusettbl;
import BLL.Kompaniatbl;
import DAL.AutobusettblRepository;
import DAL.AutobusiException;
import DAL.KompaniaException;
import DAL.KompaniaRepository;
import GUI_Model.AutobusettblTabelModel;
import GUI_Model.KompaniaComboBoxModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author detjona
 */
public class AutobusetForm extends javax.swing.JFrame {

    /**
     * Creates new form AutobusetForm
     */
    AutobusettblRepository aR = new AutobusettblRepository();
    AutobusettblTabelModel atm = new AutobusettblTabelModel();


    KompaniaRepository kR = new KompaniaRepository();
    KompaniaComboBoxModel kcbm = new KompaniaComboBoxModel();

    public AutobusetForm() throws KompaniaException {
        initComponents();
        loadAutobusetTable();
        tabelaSelectedIndexChangeAutobuset();
        loadKompaniaComboBo();
        String vargu [] = jComboBox1.getSelectedItem().toString().split(" ");
        IDkompanis.setText(vargu[0]);
        IDkompanis.disable();
    }
    
    public void loadKompaniaComboBo() throws KompaniaException{
        try {
          List<Kompaniatbl> kompanite = kR.findAll();
//          kcbm.add(kompanite);
//          jComboBox1.setModel(kcbm);
            for (int i = 0; i < kompanite.size(); i++) {
                jComboBox1.addItem(kompanite.get(i).getIDKompanise()+" "+kompanite.get(i).getEmriKompanise());
            }
        } catch (Exception e) {
        }
        
    }
    public void loadAutobusetTable() throws KompaniaException{
        try{
            List<Autobusettbl> autobuset = aR.findAll();
            atm.addList(autobuset);
            AutobusetTable.setModel(atm);
         
        }catch(AutobusiException cE){
            Logger.getLogger(AutobusiException.class.getName()).log(Level.SEVERE,null,cE);
        }
    }
    private void tabelaSelectedIndexChangeAutobuset(){
        final ListSelectionModel rowSM = AutobusetTable.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(e.getValueIsAdjusting()){
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) e.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if(selectedIndex > -1){
                    Autobusettbl c = atm.getAutobusettbl(selectedIndex);
                    emriField.setText(c.getEmriAutobusit());
                    shoferiField.setText(c.getShoferi());
                    kondukteriField.setText(c.getKondukteri());
                    IDAutobusitField.setText(c.getIDAutobusi().toString());
                    
                } //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AutobusetTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IDAutobusitField = new javax.swing.JTextField();
        emriField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        shoferiField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kondukteriField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Regjistro autobuset");

        AutobusetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID _Busit", "Emri", "Shoferi", "Kondukteri", "Linja"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AutobusetTable);

        jLabel2.setText("ID_Autobusit:");

        jLabel3.setText("Emri:");

        IDAutobusitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDAutobusitFieldActionPerformed(evt);
            }
        });

        emriField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emriFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Shoferi:");

        shoferiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoferiFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Kondukteri:");

        kondukteriField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kondukteriFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Ruaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Perditeso");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Fshij");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Pastro");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        IDkompanis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDkompanisActionPerformed(evt);
            }
        });

        jLabel6.setText("ID kompanise:");

        jLabel7.setText("Zgjidh kompanine:");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emriField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(IDAutobusitField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(shoferiField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(kondukteriField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(IDkompanis, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(IDkompanis, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(IDAutobusitField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(shoferiField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(emriField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(kondukteriField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDAutobusitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDAutobusitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDAutobusitFieldActionPerformed

    private void emriFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emriFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emriFieldActionPerformed

    private void shoferiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoferiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shoferiFieldActionPerformed

    private void kondukteriFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kondukteriFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kondukteriFieldActionPerformed

    private void IDkompanisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDkompanisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDkompanisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Autobusettbl autobuset = new Autobusettbl();
      Kompaniatbl k = new Kompaniatbl();
      k.setIDKompanise(Integer.parseInt(IDkompanis.getText()));
      autobuset.setEmriAutobusit(emriField.getText());
      autobuset.setShoferi(shoferiField.getText());
      autobuset.setKondukteri(kondukteriField.getText());
      autobuset.setIDKompanise(k);
        try {
            aR.creat(autobuset);
            JOptionPane.showMessageDialog(null, "Autobusi i shtua me sukses!");
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          int row = AutobusetTable.getSelectedRow();
       if(row == -1){
           JOptionPane.showMessageDialog(null, "Ju lutem zgjedheni autobusin per te perditesuar!");
       }
       else{
          
            Autobusettbl autobuset = new Autobusettbl();
      Kompaniatbl k = new Kompaniatbl();
      k.setIDKompanise(Integer.parseInt(IDkompanis.getText()));
      autobuset.setEmriAutobusit(emriField.getText());
      autobuset.setShoferi(shoferiField.getText());
      autobuset.setKondukteri(kondukteriField.getText());
      autobuset.setIDKompanise(k);
        try {
            aR.edit(autobuset);
            JOptionPane.showMessageDialog(null, "Autobusi i shtua me sukses!");
        } catch (Exception e) {
        }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = AutobusetTable.getSelectedRow();
       if(row == -1){
           JOptionPane.showMessageDialog(null, "Please choose a costumer to delete!");
       }
       else{
          
           try {
               Autobusettbl c = atm.getAutobusettbl(row);
               aR.delete(c);
          
               JOptionPane.showMessageDialog(null, "Autobusi eshte fshire me sukses.");
           } catch (AutobusiException ex) {
               Logger.getLogger(KompaniaException.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null, ex);
           }
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String vargu [] = jComboBox1.getSelectedItem().toString().split(" ");
        IDkompanis.setText(vargu[0]);
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        emriField.setText("");
        shoferiField.setText("");
        kondukteriField.setText("");
        IDAutobusitField.setText("");
        IDkompanis.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AutobusetTable;
    private javax.swing.JTextField IDAutobusitField;
    public static final javax.swing.JTextField IDkompanis = new javax.swing.JTextField();
    private javax.swing.JTextField emriField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kondukteriField;
    private javax.swing.JTextField shoferiField;
    // End of variables declaration//GEN-END:variables
}
