/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_View;

import BLL.Perdoruesi;
import BLL.Singleton;
import DAL.AdministrataFormException;
import DAL.AutobusiException;
import DAL.KompaniaException;
import DAL.LinjatEUdhetimitException;
import DAL.PerdoruesiRepository;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author detjona
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        usField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        autorizohuBtn = new javax.swing.JButton();
        pswField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Perdoruesi:");

        jLabel3.setText("Fjalekalimi:");

        jButton1.setText("Dil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        autorizohuBtn.setText("Autorizohu");
        autorizohuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorizohuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(autorizohuBtn))
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(pswField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autorizohuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void autorizohuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorizohuBtnActionPerformed
        // TODO add your handling code here:
            if(usField.getText().isEmpty() && pswField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nuk keni shenuar asnje te dhene \n Ju lutem shenoni emrin e perdoruesit dhe fjalekalimin!");
            }
            else if(!usField.getText().isEmpty() && pswField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nuk keni shenuar asnje fjalekalim!");
            }
            else if(usField.getText().isEmpty() && !pswField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nuk keni shenuar asnje emer te perdoruesit!");
            }
            else{
                 // TODO add your handling code here:
        try {
            PerdoruesiRepository pr = new PerdoruesiRepository();
            Perdoruesi p = pr.loginByUsernameAndPassword(usField.getText(), new String(pswField.getPassword()));
            System.out.print("p eshte: "+p);
            System.out.println("ID e puntorit eshte: "+p.getId());
            System.out.println("Username i puntorit eshte: "+p.getUsername());
            System.out.println("Password e puntorit eshte: "+p.getPassword());

//Perdoruesi p = pr.loginByUsernameAndPassword(usField.getText(), new String(pswField.getPassword()));
            if (p.getUsername().equalsIgnoreCase(usField.getText()) && p.getPassword().equalsIgnoreCase(pswField.getText())) {
               System.out.println("Roli i perdoruesit eshte: "+p.getRoliID().getEmertimi());
                this.setVisible(false);
                System.out.println("before role");
                AdministrataForm adm = new AdministrataForm();
                adm.setVisible(true);
                
                Singleton.setIDPuntorit(p.getId());
                System.out.println("ID e puntorit ehste: "+Singleton.getIdPuntorit());
            }
            else if(!p.getUsername().equalsIgnoreCase(usField.getText()) || !p.getPassword().equalsIgnoreCase(pswField.getText())){
                if(!p.getUsername().equalsIgnoreCase(usField.getText())){
                    JOptionPane.showMessageDialog(null, "Nuk ekziston puntore me kete username!");
                }
                else if(!p.getPassword().equalsIgnoreCase(pswField.getText())){
                    JOptionPane.showMessageDialog(null, "Fjalekalimi eshte gabim!");
                    
                }
            }
           
        } catch (AdministrataFormException ex) {
            JOptionPane.showMessageDialog(this, "Te dhenat jane gabim!");
            //JOptionPane.showMessageDialog(this, ex.getMessage()); 
        } catch (KompaniaException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LinjatEUdhetimitException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }       catch (AutobusiException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    
       
    }//GEN-LAST:event_autorizohuBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//           JFrame frame = new JFrame("Start up frame");
//    JButton newGameButton = new JButton("New Game");
//    frame.setLayout(new FlowLayout());
//    frame.add(newGameButton);
//    frame.setVisible(true);
//        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autorizohuBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pswField;
    private javax.swing.JTextField usField;
    // End of variables declaration//GEN-END:variables
}
